version: '3'
services:

  # The Application
  php:
    build:
      context: .
      dockerfile: ./contrib/php/php.dockerfile
    working_dir: /var/www
    volumes:
      - ./app:/var/www/app
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./public:/var/www/public
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
      - ./storage/app:/var/www/storage/app
      - ./tests:/var/www/tests

  # The Web Server
  nginx:
    image: nginx:1.12
    working_dir: /var/www
    volumes:
      - ./contrib/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443

  redis:
    image: 'redis:latest'
    restart: always
